Missing quotation mark based on below error
Waiting for changeset to be created..
Error: Failed to create changeset for the stack: foo-sessions-sam-eventbridge-example, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Template format error: The Value field of every Outputs member must evaluate to a String.

***Still getting error.